export enum ActionType {
  TOGGLE_SIDEBAR = "toggle_sideBar",
  OPEN_COMPOSE_MAIL = "open_compose_mail",
  CLOSE_COMPOSE_MAIL = "close_compose_mail",
  LOGIN = "login",
  LOGIN_SUCCESS = 'login_success',
  LOGIN_FAIL = 'login_fail',
  LOGIN_ERROR = 'login_error',
  GET_USER = "get_user",
  GET_USER_COMPLETE = "get_user_complete",
  GET_USER_ERROR = "get_user_error",
  LOGOUT = "logout",
  LOGOUT_COMPLETE = 'logout_complete',
  LOGOUT_ERROR = 'logout_error',
  FETCH_INBOX = 'fetch_inbox',
  FETCH_INBOX_COMPLETE = 'fetch_inbox_complete',
  FETCH_INBOX_ERROR = 'fetch_inbox_error',
  TOGGLE_STAR = "toggle_star",
  TOGGLE_STAR_ERROR = 'toggle_star_error',
}
